"""Account-owned relational schema, shared by PostgreSQL and local SQLite tests."""

from sqlalchemy import (
    MetaData,
    Table,
    Column,
    String,
    Integer,
    Float,
    Text,
    JSON,
    UniqueConstraint,
    ForeignKeyConstraint,
    Index,
)

metadata = MetaData(schema="jobplicator")
# Original v3 column definitions; ownership and cross-account-safe constraints follow.
LEGACY_COLUMNS = {
    "jobs": [
        {"name": "id", "type": "TEXT", "required": False, "default": None, "pk": True},
        {
            "name": "source",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "source_url",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "company",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "title",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "location",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "country",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "work_mode",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "employment_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "salary",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "posted_at",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "closing_date",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "description_raw",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "role_family",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "seniority",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "industry",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "work_rights",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "status",
            "type": "TEXT",
            "required": False,
            "default": "'discovered'",
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
        {
            "name": "updated_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "job_requirements": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "job_id",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "requirement",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "kind",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "weight",
            "type": "REAL",
            "required": False,
            "default": "0.5",
            "pk": False,
        },
        {
            "name": "hard_gate",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "category",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
    ],
    "job_matches": [
        {
            "name": "job_id",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "career_fit",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "resume_fit",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "potential_fit",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "priority_score",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "rationale",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "updated_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "evidence_matches": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "job_id",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "requirement",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "evidence_id",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "match_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "match_score",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "reason",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
    ],
    "companies": [
        {
            "name": "name",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "website",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "summary",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "industry",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "size",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "recent_context",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "updated_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "contacts": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "company",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "name",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "role",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "profile_url",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "contact_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "confidence",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "reason",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
    ],
    "applications": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "job_id",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "status",
            "type": "TEXT",
            "required": False,
            "default": "'saved'",
            "pk": False,
        },
        {
            "name": "applied_at",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "next_action",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "follow_up_date",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "notes",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "resume_version",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "cover_letter_version",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "updated_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "application_events": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "application_id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "event_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "detail",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "resume_versions": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "name",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "job_id",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "content_json",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "fit_score",
            "type": "REAL",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "cover_letters": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "job_id",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "content",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "version",
            "type": "INTEGER",
            "required": False,
            "default": "1",
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "ingestion_runs": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "source",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "status",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "found_count",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "detail",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "application_outcomes": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "application_id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "rejection_stage",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "reason_category",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "reason_known",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "notes",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "coding_questions": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "title",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "platform",
            "type": "TEXT",
            "required": False,
            "default": "'LeetCode'",
            "pk": False,
        },
        {
            "name": "leetcode_number",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "url",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "difficulty",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "primary_topic",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "secondary_topics",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "source_type",
            "type": "TEXT",
            "required": False,
            "default": "'General practice'",
            "pk": False,
        },
        {
            "name": "asked_in_real_interview",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "notes",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "coding_question_companies": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "question_id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "company",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "role",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "interview_stage",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "source_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "confidence",
            "type": "TEXT",
            "required": False,
            "default": "'Reported'",
            "pk": False,
        },
    ],
    "coding_question_attempts": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "question_id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "attempted_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
        {
            "name": "solved",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "hint_used",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "solved_within_target",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "time_taken_minutes",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "confidence",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "notes",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
    ],
    "interview_questions": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "question_text",
            "type": "TEXT",
            "required": True,
            "default": None,
            "pk": False,
        },
        {
            "name": "company",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "role",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "interview_stage",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "question_category",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "source_type",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "asked_in_real_interview",
            "type": "INTEGER",
            "required": False,
            "default": "0",
            "pk": False,
        },
        {
            "name": "answer",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "notes",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "weekly_reports": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "week_start",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "content_json",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
    "scoring_weight_history": [
        {
            "name": "id",
            "type": "INTEGER",
            "required": False,
            "default": None,
            "pk": True,
        },
        {
            "name": "weights_json",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "reason",
            "type": "TEXT",
            "required": False,
            "default": None,
            "pk": False,
        },
        {
            "name": "created_at",
            "type": "TEXT",
            "required": False,
            "default": "CURRENT_TIMESTAMP",
            "pk": False,
        },
    ],
}
TABLES = {}
REFERENCES = {
    "job_requirements": ("job_id", "jobs", "id"),
    "job_matches": ("job_id", "jobs", "id"),
    "evidence_matches": ("job_id", "jobs", "id"),
    "applications": ("job_id", "jobs", "id"),
    "resume_versions": ("job_id", "jobs", "id"),
    "cover_letters": ("job_id", "jobs", "id"),
    "application_events": ("application_id", "applications", "id"),
    "application_outcomes": ("application_id", "applications", "id"),
    "coding_question_companies": ("question_id", "coding_questions", "id"),
    "coding_question_attempts": ("question_id", "coding_questions", "id"),
}
for name, fields in LEGACY_COLUMNS.items():
    columns = [Column("owner_id", String(36), nullable=False, index=True)]
    pk = next(f["name"] for f in fields if f["pk"])
    # String natural keys are scoped to the owner; integer identities are global.
    natural = next(f for f in fields if f["pk"])["type"] != "INTEGER"
    if natural:
        columns[0].primary_key = True
    for f in fields:
        typ = (
            Integer
            if f["type"] == "INTEGER"
            else Float
            if f["type"] == "REAL"
            else Text
        )
        kw = dict(primary_key=f["pk"], nullable=not (f["required"] or f["pk"]))
        if f["pk"] and not natural:
            kw["autoincrement"] = True
        columns.append(Column(f["name"], typ, **kw))
    constraints = []
    if not natural:
        constraints.append(
            UniqueConstraint("owner_id", pk, name=f"uq_{name}_owner_key")
        )
    if name in REFERENCES:
        key, parent, target = REFERENCES[name]
        constraints.append(
            ForeignKeyConstraint(
                ["owner_id", key],
                [f"jobplicator.{parent}.owner_id", f"jobplicator.{parent}.{target}"],
                ondelete="CASCADE",
                name=f"fk_{name}_owned_parent",
            )
        )
    if name == "applications":
        constraints.append(
            UniqueConstraint("owner_id", "job_id", name="uq_application_job")
        )
    if name == "cover_letters":
        constraints.append(
            UniqueConstraint(
                "owner_id", "job_id", "version", name="uq_cover_letter_version"
            )
        )
    TABLES[name] = Table(name, metadata, *columns, *constraints)
    if name in REFERENCES:
        Index(
            f"ix_{name}_parent",
            TABLES[name].c.owner_id,
            TABLES[name].c[REFERENCES[name][0]],
        )
TABLES["profiles"] = Table(
    "profiles",
    metadata,
    Column("owner_id", String(36), primary_key=True),
    Column("content", JSON, nullable=False),
    Column("updated_at", Text, nullable=False),
)
TABLES["resume_drafts"] = Table(
    "resume_drafts",
    metadata,
    Column("owner_id", String(36), primary_key=True),
    Column("content", JSON, nullable=False),
    Column("revision", Integer, nullable=False),
    Column("updated_at", Text, nullable=False),
)
TABLES["legacy_imports"] = Table(
    "legacy_imports",
    metadata,
    Column("owner_id", String(36), primary_key=True),
    Column("fingerprint", String(64), primary_key=True),
    Column("counts", JSON, nullable=False),
    Column("created_at", Text, nullable=False),
)
# Application packages (one per job version): tailored resume, cover letter,
# answers, outreach and evidence checks. Added in migration 0002.
TABLES["application_packages"] = Table(
    "application_packages",
    metadata,
    Column("owner_id", String(36), nullable=False, index=True),
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", Text, nullable=False),
    Column("version", Integer, nullable=False),
    Column("status", Text, nullable=False),
    Column("source", Text, nullable=False),
    Column("content", JSON, nullable=False),
    Column("checks", JSON, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    UniqueConstraint("owner_id", "id", name="uq_application_packages_owner_key"),
    UniqueConstraint("owner_id", "job_id", "version", name="uq_application_package_version"),
    ForeignKeyConstraint(
        ["owner_id", "job_id"],
        ["jobplicator.jobs.owner_id", "jobplicator.jobs.id"],
        ondelete="CASCADE",
        name="fk_application_packages_owned_parent",
    ),
)
# Queue of AI package (re)generation requests picked up by the scheduled
# generator, and the company job boards synced from Greenhouse/Lever.
# Added in migration 0003.
TABLES["package_requests"] = Table(
    "package_requests",
    metadata,
    Column("owner_id", String(36), nullable=False, index=True),
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", Text, nullable=False),
    Column("note", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("done_at", Text),
    UniqueConstraint("owner_id", "id", name="uq_package_requests_owner_key"),
    ForeignKeyConstraint(
        ["owner_id", "job_id"],
        ["jobplicator.jobs.owner_id", "jobplicator.jobs.id"],
        ondelete="CASCADE",
        name="fk_package_requests_owned_parent",
    ),
)
TABLES["board_watch"] = Table(
    "board_watch",
    metadata,
    Column("owner_id", String(36), nullable=False, index=True),
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("adapter", Text, nullable=False),
    Column("token", Text, nullable=False),
    Column("label", Text, nullable=False),
    Column("last_synced_at", Text),
    Column("last_result", Text),
    UniqueConstraint("owner_id", "id", name="uq_board_watch_owner_key"),
    UniqueConstraint("owner_id", "adapter", "token", name="uq_board_watch_board"),
)
